# Generated by Django 5.2.1 on 2025-06-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_publised',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.ImageField(null=True, upload_to='posts/images'),
        ),
    ]
