# Generated by Django 5.2.1 on 2025-06-27 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_is_publised_alter_post_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_publised',
            new_name='is_published',
        ),
    ]
